apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: datadog-agent
spec:
  template:
    spec:
      containers:
      - name: agent
        image: "gcr.io/datadoghq/agent:7.66.1"
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c"]
        args:
        - |
          agent integration install -v -r -w /opt/redpanda/datadog_redpanda-*-py2.py3-none-any.whl
          agent run
        volumeMounts:
          - name: wheel-volume
            mountPath: /opt/redpanda
      volumes:
        - name: wheel-volume
          configMap:
            name: redpanda-dd-wheel